services:
  ms_kitchen_db:
    image: postgres:15
    container_name: ms_kitchen_db
    environment:
      - POSTGRES_DB=${MS_KITCHEN_DB_NAME}
      - POSTGRES_USER=${MS_KITCHEN_DB_USER}
      - POSTGRES_PASSWORD=${MS_KITCHEN_DB_PASSWORD}
    ports:
      - "5030:5432"
    volumes:
      - postgres-data-kitchen:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MS_KITCHEN_DB_USER} -d ${MS_KITCHEN_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  ms_kitchen_api:
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}"
    container_name: ms_kitchen_api
    env_file:
      - .env
    ports:
      - "80:3000"
    volumes:
      - code-kitchen:/src
    depends_on:
      ms_kitchen_db:
        condition: service_healthy

volumes:
  postgres-data-kitchen:
  code-kitchen:
