sonar.organization=bladibap
sonar.projectKey=bladiBap_ddd-proyect

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/src/Infrastructure/Persistence/Migrations/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
