const {
	MS_KITCHEN_APP_PORT,
	MS_KITCHEN_APP_PORT_EXTERNAL,
	MS_KITCHEN_APP_NAME,
	MS_KITCHEN_APP_HOST,

	MS_KITCHEN_DB_HOST,
	MS_KITCHEN_DB_PORT,
	MS_KITCHEN_DB_USER,
	MS_KITCHEN_DB_PASSWORD,
	MS_KITCHEN_DB_NAME,

	RABBITMQ_HOST,
	RABBITMQ_USERNAME,
	RABBITMQ_PASSWORD,
	RABBITMQ_VIRTUAL_HOST,

	JWT_ISSUER,
	JWT_AUDIENCE,
	JWT_SECRET,

	CONSUL_HOST,
	CONSUL_PORT,
	CONSUL_INTERVAL,
	CONSUL_TIMEOUT,
	CONSUL_DEREGISTER_AFTER,

} = process.env;

export const env = {
	MS_KITCHEN_APP_PORT: MS_KITCHEN_APP_PORT ? parseInt(MS_KITCHEN_APP_PORT, 10) : 3000,
	MS_KITCHEN_APP_PORT_EXTERNAL: MS_KITCHEN_APP_PORT_EXTERNAL ? parseInt(MS_KITCHEN_APP_PORT_EXTERNAL, 10) : 80,
	MS_KITCHEN_APP_NAME: MS_KITCHEN_APP_NAME || 'ms-kitchen',
	MS_KITCHEN_APP_HOST: MS_KITCHEN_APP_HOST || 'localhost',

	MS_KITCHEN_DB_HOST: MS_KITCHEN_DB_HOST || 'ms_kitchen_db',
	MS_KITCHEN_DB_PORT: MS_KITCHEN_DB_PORT ? parseInt(MS_KITCHEN_DB_PORT, 10) : 5432,
	MS_KITCHEN_DB_USER: MS_KITCHEN_DB_USER || 'postgres',
	MS_KITCHEN_DB_PASSWORD: MS_KITCHEN_DB_PASSWORD || 'root',
	MS_KITCHEN_DB_NAME: MS_KITCHEN_DB_NAME || 'ms_kitchen_db',

	RABBITMQ_HOST: RABBITMQ_HOST || 'rabbitmq',
	RABBITMQ_USERNAME: RABBITMQ_USERNAME || 'admin',
	RABBITMQ_PASSWORD: RABBITMQ_PASSWORD || 'StrongPassword123',
	RABBITMQ_VIRTUAL_HOST: RABBITMQ_VIRTUAL_HOST || '/',

	JWT_ISSUER: JWT_ISSUER || 'api_security',
	JWT_AUDIENCE: JWT_AUDIENCE || '*',
	JWT_SECRET: JWT_SECRET || 'DiplomadoMicroservicios2025SecretoJTWApiSecurity',

	CONSUL_HOST: CONSUL_HOST || 'host_consul',
	CONSUL_PORT: CONSUL_PORT ? parseInt(CONSUL_PORT, 10) : 8500,
	CONSUL_INTERVAL: CONSUL_INTERVAL || '10s',
	CONSUL_TIMEOUT: CONSUL_TIMEOUT || '5s',
	CONSUL_DEREGISTER_AFTER: CONSUL_DEREGISTER_AFTER || '1m'
};
