const {
	APP_PORT,
	MS_KITCHEN_DB_HOST,
	MS_KITCHEN_DB_PORT,
	MS_KITCHEN_DB_USER,
	MS_KITCHEN_DB_PASSWORD,
	MS_KITCHEN_DB_NAME,
	RABBITMQ_HOST,
	RABBITMQ_USERNAME,
	RABBITMQ_PASSWORD,
	RABBITMQ_VIRTUAL_HOST,
	JWT_ISSUER,
	JWT_AUDIENCE,
	JWT_SECRET
} = process.env;

export const env = {
	APP_PORT: APP_PORT ? parseInt(APP_PORT, 10) : 3000,
	MS_KITCHEN_DB_HOST: MS_KITCHEN_DB_HOST || 'ms_kitchen_db',
	MS_KITCHEN_DB_PORT: MS_KITCHEN_DB_PORT ? parseInt(MS_KITCHEN_DB_PORT, 10) : 5432,
	MS_KITCHEN_DB_USER: MS_KITCHEN_DB_USER || 'postgres',
	MS_KITCHEN_DB_PASSWORD: MS_KITCHEN_DB_PASSWORD || 'root',
	MS_KITCHEN_DB_NAME: MS_KITCHEN_DB_NAME || 'ms_kitchen_db',
	RABBITMQ_HOST: RABBITMQ_HOST || 'rabbitmq',
	RABBITMQ_USERNAME: RABBITMQ_USERNAME || 'admin',
	RABBITMQ_PASSWORD: RABBITMQ_PASSWORD || 'StrongPassword123',
	RABBITMQ_VIRTUAL_HOST: RABBITMQ_VIRTUAL_HOST || '/',
	JWT_ISSUER: JWT_ISSUER || 'api_security',
	JWT_AUDIENCE: JWT_AUDIENCE || '*',
	JWT_SECRET: JWT_SECRET || 'DiplomadoMicroservicios2025SecretoJTWApiSecurity'
};
