name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci

    - name: Build source code
      run: npm run build --if-present

    - name: Test code and generate report
      run: npm run test:unit

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v7
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    
